version: '3.8'

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: yozing-redis
    user: root
    ports:
      - '6379:6379'
    volumes:
      - ~/docker-yozing-redis:/bitnami'
    env_file:
      - environments/redis/.env
  db:
    image: postgres:14.1-alpine
    container_name: yozing-db
    env_file:
      - environments/postgresql/.env
    ports:
      - '5432:5432'
    volumes:
      - ~/docker-yozing:/var/lib/postgresql/data

volumes:
  db:
    driver: local