version: '3.8'

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: yozing-redis
    user: root
    ports:
      - '6379:6379'
    volumes:
      - ~/docker-yozing-redis:/bitnami'
    env_file:
      - environments/redis/.env
  db:
    image: postgres:14.1-alpine
    container_name: yozing-db
    env_file:
      - environments/postgresql/.env
    ports:
      - '5432:5432'
    volumes:
      - ~/docker-yozing:/var/lib/postgresql/data
  app:
    user: root
    container_name: yozing-app
    build:
      context: .
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - redis
      - db
  proxy:
    user: root
    container_name: yozing-proxy
    build:
      context: ./proxy
    restart: always
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/proxy_params:/etc/nginx/proxy_params
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - '80:80'
    depends_on:
      - app

volumes:
  static:
    driver: local
  media:
    driver: local
  db:
    driver: local