# Generated by Django 5.0.2 on 2024-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yozing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yozing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/yozing/', verbose_name='Image'),
        ),
    ]
